# Scheme file
# 4.5 K helium supply main line

[START]  # Position
    device = "Source"
    entry = "root"  # Entry position name
    mass_flow = 0.173  # kg/s   (fill in only when entry is "root")
[ITL-HWR]
    device = "Pipe"
    type = "Pipe50"
    length = 2.424  # m
