# Scheme file
# 4.5 K helium supply main line

[START]  # Position
    device = "Source"
    from_line = "root"   # Get fluid from other line name (from the very beginning if 'root')
    entry = "f-TTL-Start"  # Entry position name
[ITL-HWR]
    device = "Pipe"
    type = "DN50"
    length = 2.424  # m
