# Scheme of devices

[START]  # Position
    device = "Source"
    entry = "root"  # Entry position name
    mass_flow = 0.173  # kg/s   (fill in only when entry is "root")
[ITL-HWR]
    device = "Pipe"
    type = "Pipe20"
    length = 20  # m
[HWR-SSR1-1]
    device = "Pipe"
    type = "Pipe50"
    length = 50  # m
[HWR-SSR1-2]
    device = "Pipe"
    type = "Pipe20"
    length = 10  # m
