# Scheme of devices
[dev0]
    device = "Source"
    entry = "root"  # Entry point name (eg. dev2)
    mass_flow = 0.1  # kg/s   (fill in only when entry is "root"
[dev1]
    device = "Pipe"
    type = "Pipe20"
    length = 20  # m
[dev2]
    device = "Pipe"
    type = "Pipe50"
    length = 50  # m
[dev3]
    device = "Pipe"
    type = "Pipe20"
    length = 10  # m
