# Temporary values, required corrections
[DN250]
name = "Pipe DN250"
diameter = 250  # mm

[DN80]
name = "Pipe DN80"
diameter = 80  # mm

[DN65]
name = "Pipe DN65"
diameter = 65  # mm

[DN50]
name = "Pipe DN50"
diameter = 0.0545  # m

[DN40]
name = "Pipe DN40"
diameter = 40  # mm

[DN25]
name = "Pipe DN25"
diameter = 0.026

[DN20]
name = "Pipe DN20"
diameter = 0.02  # m  poprawić

[DN15]
name = "Pipe DN15"
diameter = 0.018

[ManiL]
name = "Pipe Manifold L"
diameter = 0.154

[ManiXL]
name = "Pipe Manifold XL"
diameter = 0.1623
