# Temporary values, required corrections
[DN250]
name = "Pipe DN250"
diameter = 250  # mm

[DN80]
name = "Pipe DN80"
diameter = 80  # mm

[DN65]
name = "Pipe DN65"
diameter = 65  # mm

[DN50]
name = "Pipe DN50"
diameter = 0.0545  # m

[DN40]
name = "Pipe DN40"
diameter = 40  # mm

[DN20]
name = "Pipe DN20"
diameter = 0.02  # m  poprawić

[DN15]
name = "Pipe DN15"
diameter = 15  # mm
